version: "3"
services:
  database:
    hostname: database
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=d4a8f0435b2b866f855323d7d021a79164d2e13b
    ports:
      - 13487:5432
    volumes:
      - elof_database3:/var/lib/postgresql/data
    networks:
      nw:
        aliases:
          - database
  bot:
      restart: always
      build: ./
      command: /srv/telegram_admin/run.sh
      environment:
        - DATABASE_URL=database
        - DATABASE_NAME=ebt
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=d4a8f0435b2b866f855323d7d021a79164d2e13b
        - DATABASE_HOST=database
        - DATABASE_PORT=5432
        - BOT_TOKEN=6628801834:AAFzpQzXHyVDZtFl7fQr75p7SgXY-yr7P_o
        - DOMAIN=bot.elephahealth.com
        - CHANNEL_ID=-1001550428902
        - SERVER=True
        - DEBUG=False
      ports:
        - "87:88"
      depends_on:
        - database
      hostname: bot
      networks:
        nw:
          aliases:
            - bot

networks:
  nw:
  share:
    driver:
      bridge

volumes:
  elof_database3:
