# Generated by Django 4.2 on 2023-08-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephaBot', '0002_botuser_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название файла')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='notify',
        ),
        migrations.AddField(
            model_name='botuser',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botuser',
            name='first_name',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='phone_number',
            field=models.TextField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='second_name',
            field=models.TextField(null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='email',
            field=models.TextField(null=True, verbose_name='Почта'),
        ),
        migrations.CreateModel(
            name='BotUserCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_first_name_input', models.BooleanField(default=False, null=True, verbose_name='Ввод имени')),
                ('on_second_name_input', models.BooleanField(default=False, null=True, verbose_name='Ввод фамилии')),
                ('on_email_input', models.BooleanField(default=False, null=True, verbose_name='Ввод почты')),
                ('on_phone_number_input', models.BooleanField(default=False, null=True, verbose_name='Ввод номера телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elephaBot.botuser')),
            ],
            options={
                'verbose_name': 'Состояние пользователя',
                'verbose_name_plural': 'Состояния пользователей',
            },
        ),
    ]
